### ISSUE TITLE
Write call fails with DataNotOnlineError if an ARCHIVE request is pending

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#101]
There is a flaw in the implementation of the IDS `write` call.  It is best explained by an example.  The following code shows how ingestion into IDS may be done by directly writing into IDS' main storage:
```python
>>> dataset = client.new("dataset", name="e217938", complete=False,
...                      investigation=investigation, type=datasettype)
>>> for sf in srcfiles:
...     datafile = client.new("datafile", name=sf.name)
...     dataset.datafiles.append(datafile)
... 
>>> dsrelpath = mainStorage.getrelpath(dataset)
>>> dsabspath = mainStorage.abspath(dsrelpath)
>>> dsabspath.parent.mkdir(parents=True, exist_ok=True)
>>> # Acquire an exclusive file system lock on the dataset directory in
... # main storage
... with dirlock(dsabspath, mode=fcntl.LOCK_EX) as lock:
...     dataset.create()
...     dsabspath.mkdir()
...     datafiles = dataset.datafiles
...     dataset.datafiles = []
...     for df in datafiles:
...         src_path = srcdir / df.name
...         dest_path = dsabspath / df.name
...         fstats = src_path.stat()
...         modTime = datetime.utcfromtimestamp(fstats.st_mtime).isoformat() + "Z"
...         # copy file from src_path to dest_path, calculating the crc32
...         # checksum on the fly
...         crc32 = copy_crc32(src_path, dest_path)
...         df.dataset = dataset
...         df = client.searchMatching(df, includes="1")
...         df.datafileFormat = dff.getDatafileFormat(str(src_path))
...         df.datafileModTime = modTime
...         df.datafileCreateTime = modTime
...         df.fileSize = fstats.st_size
...         df.checksum = "%x" % (crc32 & 0xffffffff)
...         df.location = str(dsrelpath / df.name)
...         df.update()
...     # Change the file system lock to a shared lock to allow the write
...     # call to access the directory
...     lock.relock(mode=fcntl.LOCK_SH)
...     client.ids.write(icat.ids.DataSelection([dataset]))
... 
```
This code works and is intended to be free of race conditions. In fact, the `write` call and the support for file system locks have been added to IDS with the intention to make such an ingest path possible. Indeed, the file system lock (if implemented in the storage plugin properly) protect this ingestion procedure from any intervening action of ids.server until the lock is released at the exit of the `with` statement.

Now, lets try the same with an intervening `ARCHIVE` request on the same dataset:
```python
>>> dataset = client.new("dataset", name="e217939", complete=False,
...                      investigation=investigation, type=datasettype)
>>> for sf in srcfiles:
...     datafile = client.new("datafile", name=sf.name)
...     dataset.datafiles.append(datafile)
... 
>>> dsrelpath = mainStorage.getrelpath(dataset)
>>> dsabspath = mainStorage.abspath(dsrelpath)
>>> dsabspath.parent.mkdir(parents=True, exist_ok=True)
>>> # Acquire an exclusive file system lock on the dataset directory in
... # main storage
... with dirlock(dsabspath, mode=fcntl.LOCK_EX) as lock:
...     dataset.create()
...     dsabspath.mkdir()
...     datafiles = dataset.datafiles
...     dataset.datafiles = []
...     # Trigger an ARCHIVE request
...     client.ids.archive(icat.ids.DataSelection([dataset]))
...     for df in datafiles:
...         src_path = srcdir / df.name
...         dest_path = dsabspath / df.name
...         fstats = src_path.stat()
...         modTime = datetime.utcfromtimestamp(fstats.st_mtime).isoformat() + "Z"
...         # copy file from src_path to dest_path, calculating the crc32
...         # checksum on the fly
...         crc32 = copy_crc32(src_path, dest_path)
...         df.dataset = dataset
...         df = client.searchMatching(df, includes="1")
...         df.datafileFormat = dff.getDatafileFormat(str(src_path))
...         df.datafileModTime = modTime
...         df.datafileCreateTime = modTime
...         df.fileSize = fstats.st_size
...         df.checksum = "%x" % (crc32 & 0xffffffff)
...         df.location = str(dsrelpath / df.name)
...         df.update()
...     # Change the file system lock to a shared lock to allow the write
...     # call to access the directory
...     lock.relock(mode=fcntl.LOCK_SH)
...     client.ids.write(icat.ids.DataSelection([dataset]))
... 
Traceback (most recent call last):
  File "<stdin>", line 30, in <module>
  File "/usr/lib/python3.6/site-packages/icat/ids.py", line 344, in write
    raise self._versionMethodError("write", '1.9', e)
  File "/usr/lib/python3.6/site-packages/icat/ids.py", line 342, in write
    self.opener.open(req)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/icat/ids.py", line 83, in http_error_default
    raise err
icat.exception.IDSDataNotOnlineError: Requested data is not online, write request refused
```

The `ARCHIVE` request does not get executed until we release the file system lock, but remains in the queue. The idea of the design is that triggering a `WRITE` request would turn the queued  `ARCHIVE` request into `WRITE_THEN_ARCHIVE` and that is exactly what would be intended here. But the `write` call checks if the corresponding data is online and refuses to trigger the `WRITE` request if this is not the case. This check is essential, because a `WRITE` on a dataset in archived state would find the directory in main storage empty and consequently delete the ZIP file from archive.

The flaw is that the implementation reused the same code that is used all over ids.server to check whether data is online. And this check does not only look at the actual state in the storage, but also for pending deferred operations. It considers a dataset to be already in archived state, if an `ARCHIVE` request is pending in the queue. And that is just wrong in this case.

**Comment by RKrahl** [comment]
One general remark: as mentioned above, when ids.server checks the status (online vs. archived vs. restoring) of a selection of data, it also looks for pending deferred operations. It is pretty obvious that this is not sensible in the case of the `write` call. I wonder if this check is not needed in general. It may have been needed in earlier versions, but I guess it got obsoleted by the introduction of the new internal locking mechanism in 1.9.0.

In any case, large parts of ids.server's code would need refactoring and this particularly concerns this status of a data selection. But this issue in the `write` call is urgent and can't wait for the big refactoring to happen.
