### ISSUE TITLE
getStatus of a Dataset having more then 1000 Datafiles throws internal error

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#42]
If a Dataset has 1000 or more Datafiles, calling getStatus for that Dataset throws an InternalException in IDS:

```python
>>> dataset = client.assertedSearch("Dataset [name='test_idsHugeDataset']")[0]
>>> client.ids.getStatus(icat.ids.DataSelection([dataset]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.3/site-packages/icat/ids.py", line 299, in getStatus
    return self.default.open(req).read().decode('ascii')
  File "/usr/lib64/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib64/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/site-packages/icat/ids.py", line 69, in http_error_default
    raise err
icat.exception.IDSInternalError: class org.icatproject.IcatException_Exception attempt to return more than 1000 entitities
```

Note that the client called getStatus for the single Dataset object alone, not for the individual Datafiles.

**Comment by RKrahl** [comment]
The same problem also occurs with delete:

```python
>>> dataset = client.assertedSearch("Dataset [name='test_idsHugeDataset']")[0]
>>> client.deleteData([dataset])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.3/site-packages/icat/client.py", line 990, in deleteData
    self.ids.delete(objs)
  File "/usr/lib/python3.3/site-packages/icat/ids.py", line 466, in delete
    self.default.open(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib64/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/site-packages/icat/ids.py", line 69, in http_error_default
    raise err
icat.exception.IDSInternalError: class org.icatproject.IcatException_Exception attempt to return more than 1000 entitities
```

**Comment by RKrahl** [comment]
Same with archive and restore.

**Comment by fisherab** [comment]
This has already been addressed in 1.6.0 where maxEntities is specified in the ids.properties file and where it may not exceed the value in the icat.properties file. If I place a dependency of the ids upon icat 4.6.0 then a better solution can be implemented as the icat can be queried for it's maxEntitites value. I will label this as a duplicate. If people are happy with a dependency upon icat 4.6.0 and higher then please say so.

**Comment by RKrahl** [comment]
I'd say, such a dependency would only be a problem, if ids 1.6.0 brings some important new feature or fix that is urgently needed by people who cannot afford to upgrade icat.server.  So the answer depends on another question: will there be any such important new stuff in ids 1.6?

I guess, the most important new thing most of us are waiting for is TopCAT 2.0, which in turn will requires icat 4.6 anyway, right?  That would imply that most people will not be very reluctant upgrading icat.server.

**Comment by kevinphippsstfc** [comment]
I agree that TopCAT 2 is going to require most facilities to move to ICAT 4.6 so having this as a dependency for ids 1.6.0 should not be a problem.
